services:
  app:
    build:
      context: ./docker/app
    container_name: app
    environment:
      - API_PORT=80
      - HOST=api
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    depends_on:
      api:
        condition: service_started
  api:
    build: .
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=demo;User=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true;
    ports:
      - 5000:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./docker/healthchecks:/healthchecks
  db:
    build: ./docker/db
    container_name: db
    hostname: db
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    healthcheck:
      test: /healthchecks/mssql.sh
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - ./docker/healthchecks:/healthchecks
